<?php

require_once 'Payment.php';

class PaypalPayment extends Payment{

	private $email;

	public function __construct($amount, $email) {
		parent::__construct($amount);
		$this->email = $email;
	}

	#[Override]
	public function process(): string {

		return "Logging into PayPal as $this->email to pay $this->amount."; // TODO: Change the autogenerated stub
	}

}